const gusi = [
  {
    id: 0,
    branch: "C",
    parent: 7,
    child: "",
    index: 72,
    title: "Ольгерд",
    music: "Кар Мэн - Чао, Бамбино!",
    theme: "ставка больше чем всё",
    location: "Игорный Дом Терпимости",
    words: ["каблуки", "фишки", "азарт", "банкноты", "мания"],
    author: "helgvar",
    link: "https://sur-noname.livejournal.com/141080.html",
    weight: 1990,
    date: new Date("2023, 2, 15"),
    starter: {
      theme: "дышать не отворачиваясь",
      music: "https://www.youtube.com/watch?v=MGgDdU1BYsA",
      location: "кисельный Берег-гард",
      words: ["река", "чайка", "крылатый", "чащоба", "волки"],
    },
  },
  {
    id: 1,
    branch: "A",
    parent: "",
    child: "",
    index: 78,
    title: "333",
    music: "https://www.youtube.com/watch?v=k3_009Uyz4M",
    theme: "С кем-то все будет хорошо",
    location: "чертоги разума",
    words: ["колосок", "Экскалибур", "клацать", "краска", "пренебречь"],
    author: "helgvar",
    link: "https://sur-noname.livejournal.com/140840.html",
    weight: 1999,
    date: new Date("2023, 1, 2"),
    starter: {
      theme: "Придёт серенький",
      music: "https://www.youtube.com/watch?v=UNA9nO0QYE4",
      location: "крематорий бизнес-класса",
      words: ["постель, излишество, искры, цеппелин, резня"],
    },
  },
  {
    id: 2,
    branch: "C",
    parent: 3,
    child: "",
    index: 109,
    title: "Сто сорок четыре дождя Себастиана Вербы",
    music: "https://youtu.be/Zw4s90dyOWI",
    theme: "перекуси поводок",
    location: "место, где много воды",
    words: ["рокфор", "азимут", "котангенс", "сныть"],
    author: "helgvar",
    link: "https://sur-noname.livejournal.com/140758.html",
    weight: 1988,
    date: new Date("2023, 1, 2"),
    starter: {
      theme: "и в печали, и в радости",
      music: "https://www.youtube.com/watch?v=UR7yvOEFJ6c",
      location: "барная стойка",
      words: ["куртуазность, мечта, подвиг, хрупкость, дуэль"],
    },
  },
  {
    id: 3,
    branch: "B",
    parent: 8,
    child: 2,
    index: 108,
    title: "Гастролёры",
    music: "https://youtube.com/watch?v=3G2itYEgL7U&si=EnSIkaIECMiOmarE",
    theme: "хорошо в деревне летом",
    location: "ДК",
    words: ["трактор", "треух", "сеновал", "ряженка", "репа"],
    author: "pomarki",
    link: "https://sur-noname.livejournal.com/140410.html",
    weight: 2011,
    date: new Date("2023, 1, 31"),
    starter: {
      theme: "перекуси поводок",
      music: "https://youtu.be/Zw4s90dyOWI",
      location: "место, где много воды",
      words: ["рокфор, азимут, котангенс, сныть"],
    },
  },
  {
    id: 4,
    branch: "A",
    parent: "",
    child: "",
    index: 76,
    title: "Верность традициям",
    music: "https://www.youtube.com/watch?v=p1pT--9cS6E",
    theme: "После стольких лет",
    location: "планета-стадион",
    words: ["рыба", "пламя", "экслибрис", "кольцо", "зонт"],
    author: "buhrun",
    link: "https://sur-noname.livejournal.com/139859.html",
    weight: 2319,
    date: new Date("2023, 1, 29"),
    starter: {
      theme: "Кончился хлебушек, а ты живи",
      music: "https://m.youtube.com/watch?v=DGWoIz5B7VM",
      location: "консерватория",
      words: ["глитч", "снасти", "коловрат", "буденовцы", "гештальт"],
    },
  },
  {
    id: 5,
    branch: "A",
    parent: "",
    child: "",
    index: 75,
    title: "Другого берега",
    music: "https://youtube.com/watch?v=o4YkrUgFqVY",
    theme: "бессмертие",
    location: "степь",
    words: ["кровь, стихи, воронье, метель, тени"],
    author: "somesin",
    link: "https://sur-noname.livejournal.com/139558.html",
    weight: 1992,
    date: new Date("2023, 1, 29"),
    starter: {
      theme: "После стольких лет",
      music: "https://www.youtube.com/watch?v=p1pT--9cS6E",
      location: "планета-стадион",
      words: ["рыба, пламя, экслибрис, кольцо, зонт"],
    },
  },
  {
    id: 6,
    branch: "A",
    parent: "",
    child: "",
    index: 74,
    title: "За рекой жизни нет",
    music: "нет",
    theme: "Жизнь не удалась, но ещё есть время начать вторую.",
    location:
      "Фронтир (колониальный на Земле, космический, фентезийный, любая отдалённая, передовая территория расширяющейся цивилизации, слабо заселённая, опасная, труднодоступная)",
    words: ["Обнял, заплакал, влюбился, каравелла, могикане"],
    author: "taipan_poison",
    link: "https://sur-noname.livejournal.com/139027.html",
    weight: 4883,
    date: new Date("2023, 1, 21"),
    starter: {
      theme: "бессмертие",
      music: "https://youtube.com/watch?v=o4YkrUgFqVY",
      location: "степь",
      words: ["кровь, стихи, воронье, метель, тени"],
    },
  },
  {
    id: 7,
    branch: "C",
    parent: 18,
    child: 0,
    index: 71,
    title: "Записка, найденная в профитроле",
    music: "https://www.youtube.com/watch?v=IvUU8joBb1Q",
    theme: "Расстояния",
    location: "Промежуток",
    words: ["интервал, дистанция, ритмика, пауза, темп"],
    author: "taipan_poison",
    link: "https://sur-noname.livejournal.com/138923.html",
    weight: 2347,
    date: new Date("2023, 1, 19"),
    starter: {
      theme: "ставка больше чем всё",
      music: "https://youtube.com/watch?v=JRa2bO1NJ34&si=EnSIkaIECMiOmarE",
      location: "Игорный Дом Терпимости",
      words: ["каблуки, фишки, азарт, банкноты, мания"],
    },
  },
  {
    id: 8,
    branch: "C",
    parent: "",
    child: 3,
    index: 107,
    title: "Тихий час",
    music: "https://www.youtube.com/watch?v=BvmfvhcOw5Y",
    theme: "Хуема",
    location: "спальня",
    words: ["колени, живот, растянута, бластер, окалина"],
    author: "taipan_poison",
    link: "https://sur-noname.livejournal.com/138716.html",
    weight: 2786,
    date: new Date("2023, 1, 19"),
    starter: {
      theme: "хорошо в деревне летом",
      music: "https://youtube.com/watch?v=3G2itYEgL7U&si=EnSIkaIECMiOmarE",
      location: "ДК",
      words: ["трактор, треух, сеновал, ряженка, репа"],
    },
  },
  {
    id: 9,
    branch: "D",
    parent: "",
    child: "",
    index: 69,
    title: "Сила каждой басовой струны",
    music: "http://www.youtube.com/watch?v=k1onj96R7YQ",
    theme: 32,
    location: "Антарктида",
    words: ["калибан, кабестан, итерация, ламантин, ратрак"],
    author: "BUHRUN",
    link: "https://sur-noname.livejournal.com/133803.html",
    weight: 3054,
    date: new Date("2018, 12, 16"),
    starter: {
      theme: "Бесстыдство",
      music: "https://youtu.be/Hfv4aarV7oQ",
      location: "Древо Сефирот",
      words: ["стоики, клинопись, стопка, адмиралтейство, шняга"],
    },
  },
  {
    id: 10,
    branch: "B",
    parent: "",
    child: "",
    index: 106,
    title: "Whiskey, Rum I Habanera!",
    music: "https://www.youtube.com/watch?v=qGyPuey-1Jw",
    theme: "Пираты Интернетского моря",
    location: "линейный корабль XVIII века",
    words: ["испанцы, крысы, кракен, выпил, акулы"],
    author: "ZLOY_BABAY",
    link: "https://sur-noname.livejournal.com/128438.html",
    weight: 5273,
    date: new Date("2017, 12, 7"),
    starter: {
      theme: "Хуема",
      music: "https://www.youtube.com/watch?v=BvmfvhcOw5Y",
      location: "спальня",
      words: ["колени, живот, растянута, бластер, окалина"],
    },
  },
  {
    id: 11,
    branch: "B",
    parent: "",
    child: "",
    index: 105,
    title: "Антивирус",
    music: "https://www.youtube.com/watch?v=sGcdcVblZ-8",
    theme: "Дисфункция",
    location: "кибергород",
    words: ["пришёл, нашёл, достал, забил, ушёл"],
    author: "KORULAG",
    link: "https://sur-noname.livejournal.com/128112.html",
    weight: 1983,
    date: new Date("2017, 10, 18"),
    starter: {
      theme: "Пираты Интернетского моря",
      music: "https://www.youtube.com/watch?v=qGyPuey-1Jw",
      location: "линейный корабль XVIII века",
      words: ["испанцы, крысы, кракен, выпил, акулы"],
    },
  },
  {
    id: 12,
    branch: "A",
    parent: "",
    child: "",
    index: 73,
    title: "Мир на Земле",
    music: "https://www.youtube.com/watch?v=2PYXa046KBY&vl=en",
    theme: "Сражение",
    location: "Побережье",
    words: ["Траншея, задворки, блеф, флуоресценция, итог"],
    author: "KORULAG",
    link: "https://sur-noname.livejournal.com/127781.html",
    weight: 1982,
    date: new Date("2017, 10, 18"),
    starter: {
      theme: "Жизнь не удалась, но ещё есть время начать вторую",
      music: "https://www.youtube.com/watch?v=42MAk4_DBFc",
      location:
        "Фронтир (колониальный на Земле, космический, фентезийный, любая отдалённая, передовая территория расширяющейся цивилизации, слабо заселённая, опасная, труднодоступная)",
      words: ["Обнял, заплакал, влюбился, каравелла, могикане"],
    },
  },
  {
    id: 13,
    branch: "A",
    parent: "",
    child: "",
    index: 72,
    title: "И выхода нет",
    music: "https://www.youtube.com/watch?v=3d…",
    theme: "охота",
    location: "middle of nowhere",
    words: ["цугцванг, ирис, чары, искра, жантильный"],
    author: "STARFLEAR",
    link: "https://sur-noname.livejournal.com/127585.html",
    weight: 1072,
    date: new Date("2017, 4, 5"),
    starter: {
      theme: "Сражение",
      music: "https://www.youtube.com/watch?v=2PYXa046KBY",
      location: "Побережье",
      words: ["Траншея,  задворки, блеф, флуоресценция, итог"],
    },
  },
  {
    id: 14,
    branch: "A",
    parent: "",
    child: "",
    index: 71,
    title: "Терновник",
    music: "https://www.youtube.com/watch?v=GaHqjStYFCM",
    theme: "Лев весной",
    location: "Инферно",
    words: ["Билет, покер, змея, стилет, уха"],
    author: "ALEXGARDT",
    link: "https://sur-noname.livejournal.com/127426.html",
    weight: 2170,
    date: new Date("2017, 3, 14"),
    starter: {
      theme: "охота",
      music: "https://www.youtube.com/watch?v=3dyNbMVfeyM",
      location: "middle of nowhere",
      words: ["цугцванг, ирис, чары, искра, жантильный"],
    },
  },
  {
    id: 15,
    branch: "A",
    parent: "",
    child: "",
    index: 70,
    title: "романсеро прозаика",
    music: "https://www.youtube.com/watch?v=3VgNoKc_Gdw",
    theme: "Прорыв",
    location: "Внутри",
    words: ["родриго, аневризма, пальчики, тринадцатый, лев"],
    author: "ВЛАД КОПЕРНИН",
    link: "https://sur-noname.livejournal.com/127132.html",
    weight: 1579,
    date: new Date("2017, 3, 11"),
    starter: {
      theme: "",
      music: "",
      location: "",
      words: [""],
    },
  },
  {
    id: 16,
    branch: "A",
    parent: "",
    child: "",
    index: 70,
    title: "Страшные соломоновы острова",
    music: "https://www.youtube.com/watch?v=3VgNoKc_Gdw",
    theme: "Прорыв",
    location: "Внутри",
    words: ["родриго, аневризма, пальчики, тринадцатый, лев"],
    author: "ВЛАД КОПЕРНИН",
    link: "https://sur-noname.livejournal.com/126909.html",
    weight: 1879,
    date: new Date("2017, 3, 11"),
    starter: {
      theme: "Лев весной",
      music: "https://www.youtube.com/watch?v=GaHqjStYFCM",
      location: "Инферно",
      words: ["Билет, покер, змея, стилет, уха"],
    },
  },
  {
    id: 17,
    branch: "A",
    parent: "",
    child: "",
    index: 69,
    title: "Забытые вещи",
    music: "https://www.youtube.com/watch?v=sJhZkXs8ZN0",
    theme: "Ожидание",
    location: "Портовый город",
    words: ["дифферент, шотландка, слаксы, выбленки, соломон"],
    author: "PATOLOGRAFER",
    link: "https://sur-noname.livejournal.com/126543.html",
    weight: 2909,
    date: new Date("2017, 2, 21"),
    starter: {
      theme: "Прорыв",
      music: "https://www.youtube.com/watch?v=3VgNoKc_Gdw",
      location: "Внутри",
      words: ["родриго, аневризма, пальчики, тринадцатый, лев"],
    },
  },
  {
    id: 18,
    branch: "C",
    parent: "",
    child: 7,
    index: 70,
    title: "Мальстрём",
    music: "https://music.yandex.ru/album/2918834",
    theme: "Конкуренция",
    location: "Мир/океан",
    words: ["балласт, сифонофоры, гичка, инвагинация, пастух"],
    author: "PATOLOGRAFER",
    link: "https://sur-noname.livejournal.com/123319.html",
    weight: 8968,
    date: new Date("2017, 1, 30"),
    starter: {
      theme: "Расстояния",
      music: "https://www.youtube.com/watch?v=IvUU8joBb1Q",
      location: "Промежуток",
      words: ["интервал, дистанция, ритмика, пауза, темп"],
    },
  },
  {
    id: 19,
    branch: "B",
    parent: "",
    child: "",
    index: 104,
    title: "В неизбежность",
    music: "https://www.youtube.com/watch?v=Gt_aDL4AG3M",
    theme: "в бегах",
    location: "в снегу",
    words: ["финики, нитка, гамаюн, синкретика, инеистый"],
    author: "FYORNE",
    link: "https://sur-noname.livejournal.com/121828.html",
    weight: 2079,
    date: new Date("2016, 11, 15"),
    starter: {
      theme: "Дисфункция",
      music: "https://www.youtube.com/watch?v=sGcdcVblZ-8",
      location: "кибергород",
      words: ["пришёл, нашёл, достал, забил, ушёл"],
    },
  },
  {
    id: 20,
    branch: "E",
    parent: "",
    child: "",
    index: 101,
    title: "Через Волгу",
    music: "https://music.yandex.ru/album/2674838",
    theme: "Анестезия",
    location: "Побережье",
    words: ["классика, нейросексизм, амадин, золотце, криорелаксанты"],
    author: "TAIPAN_POISON",
    link: "https://sur-noname.livejournal.com/121526.html",
    weight: 2942,
    date: new Date("2016, 7, 25"),
    starter: {
      theme: "мы никогда не умрем",
      music: "https://www.youtube.com/watch?v=ejEd4Jm9u2w",
      location: "какой-то другой мир",
      words: ["веснушки, блики, педаль, яичница, сжечь"],
    },
  },
  {
    id: 21,
    branch: "A",
    parent: "",
    child: "",
    index: 69,
    title: "ОЖИДАНИЕ",
    music: "https://www.youtube.com/watch?v=sJhZkXs8ZN0",
    theme: "Ожидание",
    location: "Портовый город",
    words: ["дифферент, шотландка, слаксы, выбленки, соломон"],
    author: "TWEMON",
    link: "https://sur-noname.livejournal.com/121093.html",
    weight: 3022,
    date: new Date("2016, 7, 18"),
    starter: {
      theme: "Бананы - дерьмо",
      music: "https://www.youtube.com/watch?v=g52ZXOcSIug",
      location: "Клондайк",
      words: ["стерлядка, проволочь, обструкция, ожижел, капец"],
    },
  },
  {
    id: 22,
    branch: "X",
    parent: "",
    child: "",
    index: 0,
    title: "Волосы",
    music: "нет",
    theme: "нет",
    location: "нет",
    words: ["нет"],
    author: "kprl__tot",
    link: "https://sur-noname.livejournal.com/120498.html",
    weight: 5421,
    date: new Date("2016, 4, 27"),
    starter: {
      theme: "нет",
      music: "нет",
      location: "нет",
      words: ["нет"],
    },
  },
  {
    id: 23,
    branch: "A",
    parent: "",
    child: "",
    index: 68,
    title: "Corvus corvi lupus est, или Ворон ворону волк",
    music: "http://www.youtube.com/watch?v=gaqH7kJecnM",
    theme: "кумовство",
    location: "трактир",
    words: ["пирожок, самовар, ехидна, сопелка, шмурдяк"],
    author: "PATOLOGRAFER",
    link: "https://sur-noname.livejournal.com/116793.html",
    weight: 9603,
    date: new Date("2016, 2, 28"),
    starter: {
      theme: "Ожидание",
      music: "https://www.youtube.com/watch?v=sJhZkXs8ZN0",
      location: "Портовый город",
      words: ["дифферент, шотландка, слаксы, выбленки, соломон"],
    },
  },
  {
    id: 24,
    branch: "B",
    parent: "",
    child: "",
    index: 103,
    title: "Змеиное вино",
    music: "Maximum the hormone - Zetsubou Billy",
    theme: "Вчера не было",
    location: "бар",
    words: ["мочалка, медиатор, пылесос, салат, крыло"],
    author: "TAIPAN_POISON",
    link: "https://sur-noname.livejournal.com/116330.html",
    weight: 2305,
    date: new Date("2016, 2, 25"),
    starter: {
      theme: "в бегах",
      music: "https://www.youtube.com/watch?v=Gt_aDL4AG3M",
      location: "в снегу",
      words: ["финики, нитка, гамаюн, синкретика, инеистый"],
    },
  },
  {
    id: 25,
    branch: "B",
    parent: "",
    child: "",
    index: 102,
    title: "В форме сердечка",
    music: "https://www.youtube.com/watch?v=i63cgUeSsY0",
    theme: "Драма в драмкружке",
    location: "актовый зал",
    words: ["хулиган, репетиция, гитлер, платье, влюблённость"],
    author: "LESYA_LES",
    link: "https://sur-noname.livejournal.com/116065.html",
    weight: 1983,
    date: new Date("2016, 2, 25"),
    starter: {
      theme: "Вчера не было",
      music: "https://youtu.be/lEFHwV9J7pY",
      location: "бар",
      words: ["мочалка, медиатор, пылесос, салат, крыло"],
    },
  },
  {
    id: 26,
    branch: "B",
    parent: "",
    child: "",
    index: 101,
    title: "Слон в южную ночь",
    music: "Александр Градский - Как молоды мы были",
    theme: "припомнить всё",
    location: "остров Цейлон",
    words: ["водка, кок, кот, кит, бананище"],
    author: "IISUS",
    link: "https://sur-noname.livejournal.com/115614.html",
    weight: 4221,
    date: new Date("2016, 2, 24"),
    starter: {
      theme: "Драма в драмкружке",
      music: "https://www.youtube.com/watch?v=i63cgUeSsY0",
      location: "актовый зал",
      words: ["хулиган, репетиция, гитлер, платье, влюблённость"],
    },
  },
  {
    id: 27,
    branch: "E",
    parent: "",
    child: "",
    index: 100,
    title:
      "Жесткая посадка, или Пустынный рейнджер идет вразнос (True Road Story)",
    music: "Matt Corby - Made of Stone",
    theme: "нет времени объяснять",
    location: "пустыня Мохаве",
    words: ["самовар, коронка, этюд, инкогнито, масть"],
    author: "PATOLOGRAFER",
    link: "https://sur-noname.livejournal.com/115373.html",
    weight: 6875,
    date: new Date("2016, 2, 24"),
    starter: {
      theme: "Анестезия",
      music: "https://www.youtube.com/watch?v=j7IMSuVHmJs",
      location: "Побережье",
      words: ["классика, нейросексизм, амадин, золотце, криорелаксанты"],
    },
  },
  {
    id: 28,
    branch: "B",
    parent: "",
    child: "",
    index: 100,
    title: "Сон в южную ночь",
    music: "https://www.youtube.com/watch?v=ic-QgV3hbaQ",
    theme: "нет времени объяснять",
    location: "пустыня Мохаве",
    words: ["самовар, коронка, этюд, инкогнито, масть"],
    author: "ZLOY_BABAY",
    link: "https://sur-noname.livejournal.com/115119.html",
    weight: 2292,
    date: new Date("2016, 2, 24"),
    starter: {
      theme: "припомнить всё",
      music: "Александр Градский - Как молоды мы были",
      location: "остров Цейлон",
      words: ["водка, кок, кот, кит, бананище"],
    },
  },
  {
    id: 29,
    branch: "C",
    parent: "",
    child: "",
    index: 69,
    title: "Больше нет",
    music: "https://www.youtube.com/watch?v=g7d9KM1plyg",
    theme: "Нет худа, нет добра",
    location: "Мир-кольцо",
    words: ["удар, копыта, ложка, икра, феерия"],
    author: "PATOLOGRAFER",
    link: "https://sur-noname.livejournal.com/114887.html",
    weight: 5188,
    date: new Date("2016, 2, 18"),
    starter: {
      theme: "Конкуренция",
      music: "https://music.yandex.ru/album/2918834",
      location: "Мир/океан",
      words: ["балласт, сифонофоры, гичка, инвагинация, пастух"],
    },
  },
  {
    id: 30,
    branch: "C",
    parent: 31,
    child: "",
    index: 68,
    title: "Парень со спичками",
    music: "https://www.youtube.com/watch?v=AD09ghDiyAo",
    theme: "куда ни пойдешь - всюду лес",
    location: "дебри",
    words: ["спички, ветчина, пасадобль, макабр, солнышко"],
    author: "SOMESIN",
    link: "https://sur-noname.livejournal.com/113938.html",
    weight: 1986,
    date: new Date("2016, 1, 17"),
    starter: {
      theme: "нет худа, нет добра",
      music: "https://www.youtube.com/watch?v=g7d9KM1plyg",
      location: "мир-кольцо",
      words: ["удар, копыта, ложка, икра, феерия"],
    },
  },
  {
    id: 31,
    branch: "C",
    parent: "",
    child: 30,
    index: 67,
    title: "Тогда мы были романтики",
    music: "Чугунный скороход -- Пи*оры идут",
    theme: "Гомосексуализм",
    location: "Приюпитерианский орбитальный город Нью-Симеиз",
    words: ["адюльтер, нежный, ёжики, хлебало, пеньюар"],
    author: "TAIPAN_POISON",
    link: "https://sur-noname.livejournal.com/113914.html",
    weight: 2326,
    date: new Date("2016, 1, 14"),
    starter: {
      theme: "куда ни пойдешь - всюду лес",
      music: "https://www.youtube.com/watch?v=AD09ghDiyAo",
      location: "дебри",
      words: ["спички, ветчина, пасадобль, макабр, солнышко"],
    },
  },
  {
    id: 32,
    branch: "D",
    parent: 33,
    child: 9,
    index: 68,
    title: "Мистер Медведь идет следом",
    music: "Madcon – Beggin",
    theme: "случайная встреча",
    location: "под мостом",
    words: ["ливень, дети, запонка, джайв, звездочёт"],
    author: "PATOLOGRAFER",
    link: "https://sur-noname.livejournal.com/113568.html",
    weight: 2270,
    date: new Date("2016, 1, 14"),
    starter: {
      theme: "Безмолвие",
      music: "http://www.youtube.com/watch?v=k1onj96R7YQ",
      location: "Антарктида",
      words: ["калибан, кабестан, итерация, ламантин, ратрак"],
    },
  },
  {
    id: 33,
    branch: "D",
    parent: 34,
    child: 32,
    index: 67,
    title: "...А зори здесь тихие",
    music: "Marc Cohn - Walking In Memphis",
    theme: "вечное возвращение",
    location: "верхом на звезде",
    words: ["блестки, гитара, текила, соль, Карпов"],
    author: "GAN_DRE",
    link: "https://sur-noname.livejournal.com/113365.html",
    weight: 2025,
    date: new Date("2016, 1, 5"),
    starter: {
      theme: "случайная встреча",
      music: "https://www.youtube.com/watch?v=8YVrnLa8V8M",
      location: "под мостом",
      words: ["ливень, дети, запонка, джайв, звездочёт"],
    },
  },
  {
    id: 34,
    branch: "D",
    parent: "",
    child: 33,
    index: 66,
    title:
      "Рецензия: М. Тихомиров «Всё яркое, всё горит» (Арх. «Копальхем-пресс», 2015)",
    music: "https://www.youtube.com/watch?v=4DlBHBZFm1U",
    theme: "Преследование",
    location: "Ацидалийская равнина",
    words: ["оскомина, мутиляция, гэндальф, рутина, мегалит"],
    author: "taipan_poison",
    link: "https://sur-noname.livejournal.com/112952.html",
    weight: 2395,
    date: new Date("2015, 12, 23"),
    starter: {
      theme: "вечное возвращение",
      music: "http://www.youtube.com/watch?v=KK5YGWS5H84",
      location: "верхом на звезде",
      words: ["блестки, гитара, текила, соль, Карпов"],
    },
  },
  {
    id: 35,
    branch: "A",
    parent: "",
    child: "",
    index: 67,
    title: "Алые кафтаны-3: огневой контакт",
    music: "Cypress Hill -- Tequilla Sunrise",
    theme: "Излишества",
    location: "Бордель",
    words: ["сладкий, кайман, швейцарец, доппельганглер, шоколад"],
    author: "taipan_poison",
    link: "https://sur-noname.livejournal.com/112781.html",
    weight: 2337,
    date: new Date("2015, 12, 19"),
    starter: {
      theme: "кумовство",
      music: "http://www.youtube.com/watch?v=gaqH7kJecnM",
      location: "трактир",
      words: ["пирожок, самовар, ехидна, сопелка, шмурдяк"],
    },
  },
  {
    id: 36,
    branch: "A",
    parent: "",
    child: "",
    index: 66,
    title: "Малахитовая шкатулка с зелёными человечками",
    music: "http://www.youtube.com/watch?v=uFmkNzg1V1E",
    theme: "несчастные ублюдки",
    location: "владения хозяйки медной горы",
    words: ["резкость, катана, голбец, кенотаф, помидор"],
    author: "patolografer",
    link: "https://sur-noname.livejournal.com/112637.html",
    weight: 2236,
    date: new Date("2015, 12, 19"),
    starter: {
      theme: "Излишества",
      music: "https://music.yandex.ru/album/74726/track/682854",
      location: "Бордель",
      words: ["сладкий, кайман, швейцарец, доппельганглер, шоколад"],
    },
  },
  {
    id: 37,
    branch: "C",
    parent: "",
    child: "",
    index: 66,
    title: "В пещере каменной",
    music: "а х@й его знает какая, у меня не открывается ютуб",
    theme: "деньги вечером, стулья утром",
    location: "пещеры Лейхтвейса",
    words: ["капитуляция, березовая, левкой, правые, фантасмагория"],
    author: "patolografer",
    link: "https://sur-noname.livejournal.com/112277.html",
    weight: 4315,
    date: new Date("2015, 12, 17"),
    starter: {
      theme: "Гомосексуализм",
      music: "Чугунный скороход -- Пи*оры идут",
      location: "Приюпитерианский орбитальный город Нью-Симеиз",
      words: ["адюльтер, нежный, ёжики, хлебало, пеньюар"],
    },
  },
  {
    id: 38,
    branch: "A",
    parent: "",
    child: "",
    index: 65,
    title: "Капсула ненужного",
    music: "http://www.youtube.com/watch?v=b9Cgh8-Np6c",
    theme: "математика",
    location: "проваленная явка",
    words: ["люменометр, адусация, бадьян, ключ, толкануть"],
    author: "komediante",
    link: "https://sur-noname.livejournal.com/112004.html",
    weight: 2009,
    date: new Date("2015, 12, 16"),
    starter: {
      theme: "несчастные ублюдки",
      music: "http://www.youtube.com/watch?v=uFmkNzg1V1E",
      location: "владения хозяйки медной горы",
      words: ["резкость, катана, голбец, кенотаф, помидор"],
    },
  },
  {
    id: 39,
    branch: "D",
    parent: "",
    child: "",
    index: 65,
    title: "У порога",
    music: "АукцЫон «Дорога»",
    theme: "Не за что биться",
    location: "Дорога в никуда",
    words: ["амарантовый, руны, фигурация, бездушие, сандарак"],
    author: "patolografer",
    link: "https://sur-noname.livejournal.com/111698.html",
    weight: 2745,
    date: new Date("2015, 12, 14"),
    starter: {
      theme: "Преследование",
      music: "http://www.youtube.com/watch?v=4DlBHBZFm1U",
      location: "Ацидалийская равнина",
      words: ["оскомина, мутиляция, гэндальф, рутина, мегалит"],
    },
  },
  {
    id: 40,
    branch: "C",
    parent: "",
    child: "",
    index: 65,
    title: "снег сквозь слезы",
    music: "http://www.youtube.com/watch?v=ueZZZiJMCsc",
    theme: "Не за что биться",
    location: "Дорога в никуда",
    words: ["амарантовый, руны, фигурация, бездушие, сандарак"],
    author: "kopernin",
    link: "https://sur-noname.livejournal.com/111480.html",
    weight: 2000,
    date: new Date("2015, 12, 13"),
    starter: {
      theme: "деньги вечером, стулья утром",
      music: "https://www.youtube.com/watch?v=GOVom1mfXMU",
      location: "пещеры лейхтвейса",
      words: ["капитуляция, березовая, левкой, правые, фантасмагория"],
    },
  },
  {
    id: 41,
    branch: "B",
    parent: "",
    child: "",
    index: 99,
    title: "Снежинка-девятнадцать",
    music: "https://www.youtube.com/watch?v=eQemvyyJ--g",
    theme: "если снежинка не растает",
    location: "новогодняя елка (или ее окрестности)",
    words: ["мандарин, гирлянда, серпантин, шуба, леденец"],
    author: "ceitho",
    link: "https://sur-noname.livejournal.com/111254.html",
    weight: 2357,
    date: new Date("2015, 12, 7"),
    starter: {
      theme: "нет времени объяснять",
      music: "https://www.youtube.com/watch?v=ic-QgV3hbaQ",
      location: "пустыня Мохаве",
      words: ["самовар, коронка, этюд, инкогнито, масть"],
    },
  },
  {
    id: 42,
    branch: "B",
    parent: "",
    child: "",
    index: 98,
    title: "Как я работал на орионцев",
    music: "государственный гимн РФ",
    theme: "просмотр сериала Внутри Эми Шумер",
    location: "Кремль",
    words: ["Эми, Шумер, патриот, невинность, духовность"],
    author: "taipan_poison",
    link: "https://sur-noname.livejournal.com/110872.html",
    weight: 1937,
    date: new Date("2015, 12, 6"),
    starter: {
      theme: "если снежинка не растает",
      music: "http://www.youtube.com/watch?v=eQemvyyJ--g",
      location: "новогодняя елка (или ее окрестности)",
      words: ["мандарин, гирлянда, серпантин, шуба, леденец"],
    },
  },
  {
    id: 43,
    branch: "B",
    parent: "",
    child: "",
    index: 97,
    title: "Нарушение режима",
    music: "http://www.youtube.com/watch?v=CH3rx8LhrQo",
    theme: "следственные мероприятия",
    location: "ночные улицы",
    words: ["девятимиллиметровый, оцепление, ниточки, наружка, вскрытие"],
    author: "korulag",
    link: "https://sur-noname.livejournal.com/110637.html",
    weight: 1707,
    date: new Date("2015, 9, 20"),
    starter: {
      theme: "просмотр сериала Внутри Эми Шумер",
      music: "https://www.youtube.com/watch?v=-dHUAZydTQ4",
      location: "Кремль",
      words: ["Эми, Шумер, патриот, невинность, духовность"],
    },
  },
  {
    id: 44,
    branch: "B",
    parent: "",
    child: "",
    index: 96,
    title: "Летающие окорочка",
    music: "Музыка из к/ф Серые волки Андрей Петров",
    theme: "Заговор",
    location: "Апостольский дворец, Ватикан",
    words: ["любовь, поцелуй, ЦРУ, Хитмэн, микробиология"],
    author: "taipan_poison",
    link: "https://sur-noname.livejournal.com/110348.html",
    weight: 2334,
    date: new Date("2015, 9, 9"),
    starter: {
      theme: "следственные мероприятия",
      music: "http://www.youtube.com/watch?v=CH3rx8LhrQo",
      location: "ночные улицы",
      words: ["девятимиллиметровый, оцепление, ниточки, наружка, вскрытие"],
    },
  },
  {
    id: 45,
    branch: "C",
    parent: "",
    child: "",
    index: 64,
    title: "Уицилопочтли",
    music: " http://m.youtube.com/watch?v=Ln8OgmWoyCY",
    theme: "Ограбление банка",
    location: "Ацтлан",
    words: ["Теночтитлан, Теотиуакан, Попокатепетль, Уицилопочтли, шотган"],
    author: "ceitho",
    link: "https://sur-noname.livejournal.com/110154.html",
    weight: 2359,
    date: new Date("2015, 9, 8"),
    starter: {
      theme: "Не за что биться",
      music: "http://www.youtube.com/watch?v=ueZZZiJMCsc",
      location: "Дорога в никуда",
      words: ["амарантовый, руны, фигурация, бездушие, сандарак"],
    },
  },
  {
    id: 46,
    branch: "A",
    parent: "",
    child: "",
    index: 63,
    title: "В поисках Анны Ри",
    music: "https://www.youtube.com/watch?v=ktkB96vxHOs",
    theme: "завтрак Наполеона",
    location: "Ватерлоо",
    words: ["гренадеры, Рианна, дискотека, Толстой, шампанское"],
    author: "patolografer",
    link: "https://sur-noname.livejournal.com/109875.html",
    weight: 2383,
    date: new Date("2015, 9, 7"),
    starter: {
      theme: "Ограбление банка",
      music: "http://m.youtube.com/watch?v=Ln8OgmWoyCY",
      location: "Ацтлан",
      words: ["Теночтитлан, Теотиуакан, Попокатепетль, Уицилопочтли, шотган"],
    },
  },
  {
    id: 47,
    branch: "A",
    parent: "",
    child: "",
    index: 64,
    title: "Vox nihili",
    music:
      "https://www.youtube.com/watch?v=_Zdg-AMv8tw://www.youtube.com/watch?v=_Zdg-AMv8tw",
    theme: "Назойливая муха",
    location: "библиотека",
    words: ["красный, потеха, треугольник, вольность, кеды"],
    author: "ceitho",
    link: "https://sur-noname.livejournal.com/109651.html",
    weight: 2338,
    date: new Date("2015, 9, 6"),
    starter: {
      theme: "математика",
      music: "http://www.youtube.com/watch?v=b9Cgh8-Np6c",
      location: "проваленная явка",
      words: ["люменометр, адусация, бадьян, ключ, толкануть"],
    },
  },
  {
    id: 48,
    branch: "A",
    parent: "",
    child: "",
    index: 63,
    title: "Что в твоей голове?",
    music: "https://www.youtube.com/watch?v=ktkB96vxHOs",
    theme: "завтрак Наполеона",
    location: "Ватерлоо",
    words: ["гренадеры, Рианна, дискотека, Толстой, шампанское"],
    author: "ya_zhey",
    link: "https://sur-noname.livejournal.com/109561.html",
    weight: 1226,
    date: new Date("2015, 7, 5"),
    starter: {
      theme: "Назойливая муха",
      music:
        "https://www.youtube.com/watch?v=_Zdg-AMv8tw://www.youtube.com/watch?v=_Zdg-AMv8tw",
      location: "библиотека",
      words: ["красный, потеха, треугольник, вольность, кеды"],
    },
  },
  {
    id: 49,
    branch: "A",
    parent: "",
    child: "",
    index: 62,
    title: "Всё будет спокойно",
    music: "https://www.youtube.com/watch?v=9C0xGB73Uuc",
    theme: "Разная, разная боль",
    location: "берег",
    words: ["мечта, вера, доблесть, вкус, солнце"],
    author: "korulag",
    link: "https://sur-noname.livejournal.com/108758.html",
    weight: 1996,
    date: new Date("2015, 6, 24"),
    starter: {
      theme: "завтрак Наполеона",
      music: "https://www.youtube.com/watch?v=ktkB96vxHOs",
      location: "Ватерлоо",
      words: ["гренадеры, Рианна, дискотека, Толстой, шампанское"],
    },
  },
  {
    id: 50,
    branch: "B",
    parent: "",
    child: "",
    index: 95,
    title: "Эра милосердия",
    music: "https://www.youtube.com/watch?v=gE3-q-aoFZI",
    theme: "мир хижинам",
    location: "Виннипег",
    words: ["росомаха, выхрест, гурт, престидижитатор, Золя"],
    author: "korulag",
    link: "https://sur-noname.livejournal.com/108427.html",
    weight: 1678,
    date: new Date("2015, 6, 21"),
    starter: {
      theme: "Заговор",
      music: "https://www.youtube.com/watch?v=H3B-q8AZnAs",
      location: "Апостольский дворец, Ватикан",
      words: ["любовь, поцелуй, ЦРУ, Хитмэн, микробиология"],
    },
  },
  {
    id: 51,
    branch: "A",
    parent: "",
    child: "",
    index: 61,
    title: "Переворот",
    music: "https://www.youtube.com/watch?v=vZCkuztj3Jg",
    theme: "Политические интриги",
    location: "деревянный биплан",
    words: ["руль, бензобак, бюджет, президент, скандал"],
    author: "helgvar",
    link: "https://sur-noname.livejournal.com/108218.html",
    weight: 1997,
    date: new Date("2015, 6, 20"),
    starter: {
      theme: "Разная, разная боль",
      music: "https://www.youtube.com/watch?v=9C0xGB73Uuc",
      location: "берег",
      words: ["мечта, вера, доблесть, вкус, солнце"],
    },
  },
  {
    id: 52,
    branch: "B",
    parent: "",
    child: "",
    index: 95,
    title: "Восходитель",
    music: "https://www.youtube.com/watch?v=OkNlIWKjFAI",
    theme: "Восхождение Юпитер (не планеты, а героини)",
    location: "Вся Земля",
    words: ["Шон Бин, примитивизм, пошлость, стрелок, Шарп"],
    author: "helgvar",
    link: "https://sur-noname.livejournal.com/107817.html",
    weight: 1998,
    date: new Date("2015, 6, 20"),
    starter: {
      theme: "мир хижинам",
      music: "https://www.youtube.com/watch?v=gE3-q-aoFZI",
      location: "Виннипег",
      words: ["росомаха, выхрест, гурт, престидижитатор, Золя"],
    },
  },
  {
    id: 53,
    branch: "A",
    parent: "",
    child: "",
    index: 60,
    title: "Гламурная бронетехника добрых советов",
    music: "https://www.youtube.com/watch?v=It8hdsqA170#t=19",
    theme: "Вскрытие покажет",
    location: "танк",
    words: ["армянин, синегнойка, подкалиберный, янус, пелотон"],
    author: "korulag",
    link: "https://sur-noname.livejournal.com/107289.html",
    weight: 2022,
    date: new Date("2015, 6, 2"),
    starter: {
      theme: "Политические интриги",
      music: "https://www.youtube.com/watch?v=vZCkuztj3Jg",
      location: "деревянный биплан",
      words: ["руль, бензобак, бюджет, президент, скандал"],
    },
  },
  {
    id: 54,
    branch: "B",
    parent: "",
    child: "",
    index: 94,
    title: "Юпитер",
    music: "http://www.youtube.com/watch?v=WREobnmYO4M#t=19",
    theme: "Планеты нетрудно упомнить",
    location: "Гонолулу",
    words: ["плутон, альтернатива, пеньюар, релятивистский, дайсон"],
    author: "korulag",
    link: "https://sur-noname.livejournal.com/107054.html",
    weight: 1730,
    date: new Date("2015, 6, 2"),
    starter: {
      theme: "Восхождение Юпитер (не планеты, а героини)",
      music: "https://www.youtube.com/watch?v=OkNlIWKjFAI",
      location: "вся Земля",
      words: ["Шон Бин, примитивизм, пошлость, стрелок, Шарп"],
    },
  },
  {
    id: 55,
    branch: "B",
    parent: "",
    child: "",
    index: 93,
    title: "Shanghai Reggae: In memorium J.G.B.",
    music: "https://www.youtube.com/watch?v=nGW8Lazguis ",
    theme: "С милым рай и в шалаше",
    location: "Консульство",
    words: ["лук, канонада, лошадь, смерть, хохот"],
    author: "patolografer",
    link: "https://sur-noname.livejournal.com/106978.html",
    weight: 1991,
    date: new Date("2015, 5, 7"),
    starter: {
      theme: "Планеты нетрудно упомнить",
      music: "http://www.youtube.com/watch?v=WREobnmYO4M#t=19",
      location: "Гонолулу",
      words: ["плутон, альтернатива, пеньюар, релятивистский, дайсон"],
    },
  },
  {
    id: 56,
    branch: "A",
    parent: "",
    child: "",
    index: 59,
    title: "Ждущие в бездне",
    music: "https://www.youtube.com/watch?v=UoMX-w1rQlU",
    theme: "Он под деревом сидит",
    location: "Орбитальная станция",
    words: ["лукошко, семечки, подосиновик, рыжий, доктор"],
    author: "patolografer",
    link: "https://sur-noname.livejournal.com/106601.html",
    weight: 1999,
    date: new Date("2015, 5, 7"),
    starter: {
      theme: "Вскрытие покажет",
      music: "https://www.youtube.com/watch?v=It8hdsqA170#t=19",
      location: "танк",
      words: ["армянин,синегнойка,подкалиберный,янус, пелотон"],
    },
  },
  {
    id: 57,
    branch: "B",
    parent: "",
    child: "",
    index: 92,
    title: "Невольник чести",
    music: "https://music.yandex.ru/album/1893023/track/17198840",
    theme: "на самом деле",
    location: "ну это самое",
    words: ["короче, как бы, типа, ваще, угарно"],
    author: "helgvar",
    link: "https://sur-noname.livejournal.com/106263.html",
    weight: 0,
    date: new Date("2015, 2, 21"),
    starter: {
      theme: "С милым рай и в шалаше",
      music: "https://www.youtube.com/watch?v=nGW8Lazguis",
      location: "Консульство",
      words: ["лук, канонада, лошадь, смерть, хохот"],
    },
  },

];



export { gusi };

// А - a
// Б - b
// В - c
// Г - d
// Д - e
//https://sur-noname.livejournal.com/?skip=110

// year, month, day

/* {
  id: 0,
  branch: "",
  parent: "",
  child: "",
  index: 0,
  title: "",
  music: "",
  theme: "",
  location: "",
  words: [""],
  author: "",
  link: "",
  weight: 0,
  date: new Date(""),
  starter: {
    theme: "",
    music: "",
    location: "",
    words: [""],
  },
}, */
